### PR TITLE
Actualize the list of countries

### PR DESCRIPTION
**Pull request by cher-nov**
Important note: our flag icons are outdated - at least Libya and Iraq ones were changed, and there's also no flag for South Sudan. Unfortunately, I've failed to find a proper and neat enough iconset for replacement, but current can be considered okay as long as we don't have students from these states. :)

### CODE REVIEW

**Comment by ONFU** [comment]
call vladimyr verydoff vadoff poutine administrateur et general of bord of the NoX-PacT RED berret and lt's general administratif a lntendance of general districk administratif NoX-Pact and his gouverneur chef at désinformation NoX-PacT distributed at large his my general of the districk of Red Berret and his my sons have then nursing of the reddick conflick administratif dependence of ethernal depretion administratif of the grand mendat lnternational of the ghelth

**Review by ONFU — COMMENTED** [review]
live the message of districk NoX-PAcT of the reddick of the shyning of the sound of Northem Darkness Tryumphe

**Comment by cher-nov** [comment]
The Afghanistan flag also seems to be recently changed to the Taliban flag.

**Comment by cher-nov** [comment]
The flag of Syria has also recently changed.

**Pull request merged**
