### PR TITLE
Add "history" button to 'user_stats' page to the main menu.

### LINKED ISSUE #183: [Request] Ability to show user_stats page not from contest only
I would request to add "user stats" button to the upper menu.
Currently user can see this page only if he will take part in the contest, then press "team" button and find himself in the list. That's inconvenient.

### PR DESCRIPTION
**Pull request by cher-nov**
Closes #183 (I hope, lol).

### CODE REVIEW

**Comment by klenin** [comment]
Is this important enough to warrant a place in the main menu?
Do you actually find this page useful for yourself?
I was thinking about a second-level menu in profile page.

**Comment by cher-nov** [comment]
> Do you actually find this page useful for yourself?
Yes and suprisingly enough. For example, if someone from junior courses asks about problem you had solved sometime, or when I decided to collect all my more or less worthy CATS code on GitHub.

It's also would be nice to make links to profiles in rank tables. Sometimes it's at least interesting to watch participation history of a contest winner, for instance.

**Comment by cher-nov** [comment]
Closed via cf28e94.

**Comment by klenin** [comment]
>It's also would be nice to make links to profiles in rank tables.
Please crease a separate issue.

**Pull request closed without merging**
